services:
  shade-agent-app:
    environment:
      AGENT_CONTRACT_ID: ${AGENT_CONTRACT_ID}
      SPONSOR_ACCOUNT_ID: ${SPONSOR_ACCOUNT_ID}
      SPONSOR_PRIVATE_KEY: ${SPONSOR_PRIVATE_KEY}
    platform: linux/amd64
    image: pivortex/my-first-agent@sha256:c5ffdacafe11117c8261f97854617bcfdd8487ab52c66fc5f299d56a176f1326
    container_name: shade-agent-app
    ports:
      - 3000:3000
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    restart: always
